### ISSUE TITLE
Form Framework doc use/review - Mike Wells

### ISSUE THREAD

**Issue by ZoeSimon** [bcgov/lucy-web#474]
**Describe the Task**
we want Mike Wells to use the existing documentation on the form framework and call out where he feels there are gaps/or where things arent clear. 

Andrea and Raj have put significant time into the documentation and it needs some fresh eyes.

Form Framework Documentation Review: 
- [ ] @micheal-w-wells Use/Review form framework and raise questions/gaps so the team can address.

**Comment by micheal-w-wells** [comment]
Step 1 fails from no sudo
Step 2 fails as it assumes the users system has type script installed already

**Comment by micheal-w-wells** [comment]
Step 2 failure output after installing typescript:
```
lucy-web$ ts-node api/api_sources/scripts/create.schema.ts -s testSchema

/usr/local/lib/node_modules/ts-node/src/index.ts:434
    return new TSError(diagnosticText, diagnosticCodes)
           ^
TSError: ⨯ Unable to compile TypeScript:
api/api_sources/scripts/create.schema.ts:23:21 - error TS2307: Cannot find module 'fs' or its corresponding type declarations.

23 import * as fs from 'fs';
                       ~~~~
api/api_sources/scripts/create.schema.ts:24:27 - error TS2307: Cannot find module 'minimist' or its corresponding type declarations.

24 import * as minimist from 'minimist';
                             ~~~~~~~~~~
api/api_sources/scripts/create.schema.ts:25:20 - error TS2307: Cannot find module 'underscore' or its corresponding type declarations.

25 import * as _ from 'underscore';
                      ~~~~~~~~~~~~
api/api_sources/scripts/create.schema.ts:40:35 - error TS2580: Cannot find name 'process'. Do you need to install type definitions for node? Try `npm i @types/node`.

40     const options: any = minimist(process.argv.slice(2));
                                     ~~~~~~~
api/api_sources/scripts/create.schema.ts:45:13 - error TS2580: Cannot find name 'process'. Do you need to install type definitions for node? Try `npm i @types/node`.

45             process.exit(0);
               ~~~~~~~
api/api_sources/scripts/create.schema.ts:53:9 - error TS2580: Cannot find name 'process'. Do you need to install type definitions for node? Try `npm i @types/node`.

53         process.exit(0);
           ~~~~~~~
api/api_sources/scripts/create.schema.ts:56:20 - error TS2339: Property 'includes' does not exist on type 'string'.

56     if (schemaName.includes('Schema')) {
                      ~~~~~~~~
api/api_sources/scripts/create.schema.ts:84:13 - error TS2580: Cannot find name 'process'. Do you need to install type definitions for node? Try `npm i @types/node`.

84             process.exit(0);
               ~~~~~~~
api/api_sources/scripts/create.schema.ts:91:13 - error TS2580: Cannot find name 'process'. Do you need to install type definitions for node? Try `npm i @types/node`.

91             process.exit(0);
               ~~~~~~~

    at createTSError (/usr/local/lib/node_modules/ts-node/src/index.ts:434:12)
    at reportTSError (/usr/local/lib/node_modules/ts-node/src/index.ts:438:19)
    at getOutput (/usr/local/lib/node_modules/ts-node/src/index.ts:578:36)
    at Object.compile (/usr/local/lib/node_modules/ts-node/src/index.ts:775:32)
    at Module.m._compile (/usr/local/lib/node_modules/ts-node/src/index.ts:858:43)
    at Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Object.require.extensions.(anonymous function) [as .ts] (/usr/local/lib/node_modules/ts-node/src/index.ts:861:12)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)

```

**Comment by micheal-w-wells** [comment]
There should be a package.json defining all requirements rather than a list of global npm install commands.

**Comment by jakemorr** [comment]
Thanks @micheal-w-wells we will follow up and let you know when we are ready for a retry.

**Comment by fwpushan** [comment]
@micheal-w-wells 
Use local sandbox env by running the following steps
** INSTALL DOCKER **
1. in /api dir run **make local** or **make local-debug**
2. in same /api dir run **make api** to shell into api sandbox container 
3. Now run all commands

**Comment by micheal-w-wells** [comment]
@fwpushan thanks for instructions above, but I'm hoping that the feedback I gave here can result in updates to the doc, and if you ping me from the PR I'll give it another go from scratch from cloning the repo.

**Comment by fwpushan** [comment]
@micheal-w-wells, Thank you for feedback, we are updating FormFrameworkReadMe.md

**Comment by ZoeSimon** [comment]
@micheal-w-wells please review before closing
