### ISSUE TITLE
Make swagger schema validation present a more readable error (for all new endpoints).

### ISSUE THREAD

**Issue by micheal-w-wells** [bcgov/lucy-web#792]
Make swagger schema validation present a more readable error (for all new endpoints).

Right now the stack dump that is presented if the schema of the request is invalid does not give the user hints as to what the problem is.  This task is to make that error more clear for the API consumer as to what field(s) are the problem.

- [x] if i send a bad request it will give me a readable error.

_Originally posted by @micheal-w-wells in https://github.com/bcgov/lucy-web/issues/776#issuecomment-673519365_

**Comment by micheal-w-wells** [comment]
took all day so i'm calling it a 3

**Comment by micheal-w-wells** [comment]
@NickPhura I swapped out what we're using for validation because what we had wouldn't get any more specific than 'the schema is wrong'.  I can get the new one to log a really nice message but I cannot for the life of me get it to put that output in the response body without getting a really weird type error.

```
  validator.validateModel(args.swagger.params.postBody.value, 'ActivityPostBody', (err:any, result: any ) => {
      const errorString = result.humanReadable();
      console.log(errorString)
      console.log(typeof errorString)
        res = errorString
        //return sendResponse(res, 400);
      
  })

```


With the return statement above commented out, I get this:

```
> lucy-api-mobile@0.0.0 start /home/mw/lucy-web/api-mobile
> ts-node app

[2020-08-14 16:55:03] (info) (app): start api - started api-mobile on port 3002  
[2020-08-14 16:55:05] (info) (app): POST /api/activity  
errorString: Missing required property:
         - At ActivityPostBody/data

Additional Property:
         - At ActivityPostBody/data_wrong_name

Additional Property:
         - At ActivityPostBody/locationAndGeometry/test

typeof errorString: string
res: Missing required property:
         - At ActivityPostBody/data

Additional Property:
         - At ActivityPostBody/data_wrong_name

Additional Property:
         - At ActivityPostBody/locationAndGeometry/test

typeof res: string
res.writeHead is not a function
```

uncommented:

```
> lucy-api-mobile@0.0.0 start /home/mw/lucy-web/api-mobile
> ts-node app

[2020-08-14 16:58:29] (info) (app): start api - started api-mobile on port 3002  
[2020-08-14 16:58:36] (info) (app): POST /api/activity  
errorString: Missing required property:
         - At ActivityPostBody/data

Additional Property:
         - At ActivityPostBody/data_wrong_name

Additional Property:
         - At ActivityPostBody/locationAndGeometry/test

typeof errorString: string
res: Missing required property:
         - At ActivityPostBody/data

Additional Property:
         - At ActivityPostBody/data_wrong_name

Additional Property:
         - At ActivityPostBody/locationAndGeometry/test

typeof res: string
Unhandled rejection TypeError: Cannot read property 'humanReadable' of undefined
    at /home/mw/lucy-web/api-mobile/src/controllers/activity-controller.ts:41:34
    at /home/mw/lucy-web/api-mobile/node_modules/swagger-object-validator/lib/handler.js:24:17
    at tryCatcher (/home/mw/lucy-web/api-mobile/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/mw/lucy-web/api-mobile/node_modules/bluebird/js/release/promise.js:547:31)
    at Promise._settlePromise (/home/mw/lucy-web/api-mobile/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromise0 (/home/mw/lucy-web/api-mobile/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/home/mw/lucy-web/api-mobile/node_modules/bluebird/js/release/promise.js:725:18)
    at _drainQueueStep (/home/mw/lucy-web/api-mobile/node_modules/bluebird/js/release/async.js:93:12)
    at _drainQueue (/home/mw/lucy-web/api-mobile/node_modules/bluebird/js/release/async.js:86:9)
    at Async._drainQueues (/home/mw/lucy-web/api-mobile/node_modules/bluebird/js/release/async.js:102:5)
    at Immediate.Async.drainQueues (/home/mw/lucy-web/api-mobile/node_modules/bluebird/js/release/async.js:15:14)
    at runCallback (timers.js:810:20)
    at tryOnImmediate (timers.js:768:5)
    at processImmediate [as _immediateCallback] (timers.js:745:5)
```

**Comment by NickPhura** [comment]
Updated the new validation for the Activity POST endpoint.
No other endpoints have any request body objects to validate at this point.
